name: classes_manager
description: "A class management application for tutors"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  sqflite: ^2.3.2
  path: ^1.8.3
  intl: ^0.19.0
  path_provider: ^2.1.2
  excel: ^4.0.2
  csv: ^5.1.1
  flutter_colorpicker: ^1.0.3
  url_launcher: ^6.2.5
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
